on:
  push:
    branches:
      - main # default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - run: pacman --noconfirm -Syu
      - run: pacman --noconfirm -S libjxl git nodejs npm imagemagick libwebp libavif libheif git git-lfs
      - run: npm install -g yarn
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          lfs: true
          submodules: true
      - run: (cd assets/art; git lfs install; git lfs pull) # github what the fuck
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: own3d/bunny-action@main
        env:
          BUNNY_API_ACCESS_KEY: ${{ secrets.BUNNY_API_ACCESS_KEY }}
          BUNNY_STORAGE_HOSTNAME: storage.bunnycdn.com
          BUNNY_STORAGE_USERNAME: lotte-chir-rs
          BUNNY_STORAGE_PASSWORD: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
          BUNNY_PULL_ZONE_ID: 1893884
        with:
          args: deploy --dir=public
